### ISSUE TITLE
no forecast, card shows only the past

### ISSUE THREAD

**Issue by lockenkop** [Makin-Things/weather-radar-card#10] opened 2022-05-23 13:41 UTC
![grafik](https://user-images.githubusercontent.com/96825051/169832142-5d9248ee-227d-4103-b475-5979275cf326.png)
Is the forecast not usable?

**Comment by Makin-Things** [comment] 2022-05-23 21:41
Duplicate of #7

**Closed by Makin-Things** 2022-05-23 21:41 UTC
Labels: duplicate
